declare var __DEV__: boolean
declare var __PROD__: boolean
declare var __VERSION__: string
declare namespace NodeJS {
    interface ProcessEnv {
        GITHUB_TOKEN:string
        GITHUB_STATE:string
        DOTNET_NOLOGO:string
        USER:string
        npm_config_user_agent:string
        CI:string
        RUNNER_ENVIRONMENT:string
        GITHUB_ENV:string
        PIPX_HOME:string
        npm_node_execpath:string
        JAVA_HOME_8_X64:string
        SHLVL:string
        HOME:string
        OLDPWD:string
        RUNNER_TEMP:string
        GITHUB_EVENT_PATH:string
        npm_package_json:string
        JAVA_HOME_11_X64:string
        PIPX_BIN_DIR:string
        GITHUB_REPOSITORY_OWNER:string
        GRADLE_HOME:string
        ANDROID_NDK_LATEST_HOME:string
        JAVA_HOME_21_X64:string
        GITHUB_RETENTION_DAYS:string
        GITHUB_REPOSITORY_OWNER_ID:string
        POWERSHELL_DISTRIBUTION_CHANNEL:string
        AZURE_EXTENSION_DIR:string
        GITHUB_HEAD_REF:string
        SYSTEMD_EXEC_PID:string
        GITHUB_GRAPHQL_URL:string
        NVM_DIR:string
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE:string
        GOROOT_1_21_X64:string
        JAVA_HOME_17_X64:string
        ImageVersion:string
        LOGNAME:string
        RUNNER_OS:string
        GITHUB_API_URL:string
        GOROOT_1_22_X64:string
        SWIFT_PATH:string
        pnpm_config_verify_deps_before_run:string
        CHROMEWEBDRIVER:string
        GOROOT_1_23_X64:string
        JOURNAL_STREAM:string
        GITHUB_WORKFLOW:string
        _:string
        MEMORY_PRESSURE_WATCH:string
        npm_config_registry:string
        ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE:string
        GITHUB_RUN_ID:string
        GITHUB_REF_TYPE:string
        BOOTSTRAP_HASKELL_NONINTERACTIVE:string
        GITHUB_WORKFLOW_SHA:string
        GITHUB_BASE_REF:string
        ImageOS:string
        GITHUB_WORKFLOW_REF:string
        GITHUB_ACTION_REPOSITORY:string
        ENABLE_RUNNER_TRACING:string
        npm_config_node_gyp:string
        PATH:string
        ANT_HOME:string
        DOTNET_MULTILEVEL_LOOKUP:string
        RUNNER_TRACKING_ID:string
        INVOCATION_ID:string
        RUNNER_TOOL_CACHE:string
        NODE:string
        npm_package_name:string
        GITHUB_ACTION:string
        GITHUB_RUN_NUMBER:string
        GITHUB_TRIGGERING_ACTOR:string
        RUNNER_ARCH:string
        XDG_RUNTIME_DIR:string
        AGENT_TOOLSDIRECTORY:string
        npm_config_frozen_lockfile:string
        LANG:string
        VCPKG_INSTALLATION_ROOT:string
        CONDA:string
        RUNNER_NAME:string
        XDG_CONFIG_HOME:string
        GITHUB_REF_NAME:string
        GITHUB_REPOSITORY:string
        npm_lifecycle_script:string
        ANDROID_NDK_ROOT:string
        GITHUB_ACTION_REF:string
        DEBIAN_FRONTEND:string
        SHELL:string
        GITHUB_REPOSITORY_ID:string
        GITHUB_ACTIONS:string
        npm_package_version:string
        npm_config_verify_deps_before_run:string
        npm_lifecycle_event:string
        NODE_PATH:string
        GITHUB_REF_PROTECTED:string
        GITHUB_WORKSPACE:string
        ACCEPT_EULA:string
        GITHUB_JOB:string
        GITHUB_SHA:string
        GITHUB_RUN_ATTEMPT:string
        GITHUB_REF:string
        GITHUB_ACTOR:string
        ANDROID_SDK_ROOT:string
        GITHUB_PATH:string
        JAVA_HOME:string
        PWD:string
        GITHUB_ACTOR_ID:string
        RUNNER_WORKSPACE:string
        npm_execpath:string
        HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS:string
        GITHUB_EVENT_NAME:string
        HOMEBREW_NO_AUTO_UPDATE:string
        ANDROID_HOME:string
        GITHUB_SERVER_URL:string
        GECKOWEBDRIVER:string
        GHCUP_INSTALL_BASE_PREFIX:string
        GITHUB_OUTPUT:string
        EDGEWEBDRIVER:string
        PNPM_SCRIPT_SRC_DIR:string
        npm_config__jsr_registry:string
        npm_command:string
        ANDROID_NDK:string
        SGX_AESM_ADDR:string
        CHROME_BIN:string
        SELENIUM_JAR_PATH:string
        MEMORY_PRESSURE_WRITE:string
        ANDROID_NDK_HOME:string
        GITHUB_STEP_SUMMARY:string
        INIT_CWD:string
    }
}
