declare var __DEV__: boolean
declare var __PROD__: boolean
declare var __VERSION__: string
declare namespace NodeJS {
    interface ProcessEnv {
        ACLOCAL_PATH:string
        ALLUSERSPROFILE:string
        APPDATA:string
        APPLICATION_ID:string
        ChocolateyInstall:string
        ChocolateyLastPathUpdate:string
        CHROME_CRASHPAD_PIPE_NAME:string
        COLORTERM:string
        COMMONPROGRAMFILES:string
        "CommonProgramFiles(x86)": string
        CommonProgramW6432:string
        COMPUTERNAME:string
        COMSPEC:string
        CONFIG_SITE:string
        DISCORD_TOKEN:string
        DISPLAY:string
        DriverData:string
        EFC_3368_1262719628:string
        EFC_3368_1592913036:string
        EFC_3368_2283032206:string
        EFC_3368_2775293581:string
        EFC_3368_3789132940:string
        EXEPATH:string
        GIT_ASKPASS:string
        GUILD_ID1:string
        HOME:string
        HOMEDRIVE:string
        HOMEPATH:string
        HOSTNAME:string
        INFOPATH:string
        INIT_CWD:string
        LANG:string
        LOCALAPPDATA:string
        LOGONSERVER:string
        MANPATH:string
        MINGW_CHOST:string
        MINGW_PACKAGE_PREFIX:string
        MINGW_PREFIX:string
        MONGOURI:string
        MSYS:string
        MSYSTEM:string
        MSYSTEM_CARCH:string
        MSYSTEM_CHOST:string
        MSYSTEM_PREFIX:string
        NODE:string
        NODE_ENV:string
        npm_command:string
        npm_config_frozen_lockfile:string
        npm_config_global_bin_dir:string
        npm_config_node_gyp:string
        npm_config_registry:string
        npm_config_user_agent:string
        npm_config_verify_deps_before_run:string
        npm_config__jsr_registry:string
        npm_execpath:string
        npm_lifecycle_event:string
        npm_lifecycle_script:string
        npm_node_execpath:string
        npm_package_json:string
        npm_package_name:string
        npm_package_version:string
        NUMBER_OF_PROCESSORS:string
        OneDrive:string
        OneDriveConsumer:string
        ORIGINAL_PATH:string
        ORIGINAL_TEMP:string
        ORIGINAL_TMP:string
        ORIGINAL_XDG_CURRENT_DESKTOP:string
        OS:string
        PATH:string
        PATHEXT:string
        PKG_CONFIG_PATH:string
        PKG_CONFIG_SYSTEM_INCLUDE_PATH:string
        PKG_CONFIG_SYSTEM_LIBRARY_PATH:string
        PLINK_PROTOCOL:string
        pnpm_config_verify_deps_before_run:string
        PNPM_HOME:string
        PNPM_SCRIPT_SRC_DIR:string
        PROCESSOR_ARCHITECTURE:string
        PROCESSOR_IDENTIFIER:string
        PROCESSOR_LEVEL:string
        PROCESSOR_REVISION:string
        ProgramData:string
        PROGRAMFILES:string
        "ProgramFiles(x86)": string
        ProgramW6432:string
        PROMPT:string
        PSModulePath:string
        PUBLIC:string
        PWD:string
        SESSIONNAME:string
        SHELL:string
        SHLVL:string
        SSH_ASKPASS:string
        SYSTEMDRIVE:string
        SYSTEMROOT:string
        TEMP:string
        TERM:string
        TERM_PROGRAM:string
        TERM_PROGRAM_VERSION:string
        TMP:string
        TMPDIR:string
        USERDOMAIN:string
        USERDOMAIN_ROAMINGPROFILE:string
        USERNAME:string
        USERPROFILE:string
        VSCODE_GIT_ASKPASS_EXTRA_ARGS:string
        VSCODE_GIT_ASKPASS_MAIN:string
        VSCODE_GIT_ASKPASS_NODE:string
        VSCODE_GIT_IPC_HANDLE:string
        WINDIR:string
        ZES_ENABLE_SYSMAN:string
        __COMPAT_LAYER:string
    }
}
