name: Build & Deploy All Bots

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bot:
          - name: russell
            folder: triviabot
            process: russell
          - name: opie
            folder: opie-bot
            process: opie
          - name: genie
            folder: genie-bot
            process: genie

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{secrets.VPS_HOST}} >> ~/.ssh/known_hosts

      - name: Install & Build ${{ matrix.bot.name }}
        run: |
          pnpm install --ignore-scripts
          cd ${{ matrix.bot.folder }}
          pnpm run build || echo "No build script; skipping"

      - name: SSH Deploy ${{ matrix.bot.name }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }} # e.g. root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # go to your repo root
            cd /root/DiscordBots

            # pull the latest
            git pull origin main

            # ensure pnpm is available (installs globally if needed)
            if ! command -v pnpm > /dev/null; then
                npm install -g pnpm@latest
            fi

            # install all workspace deps
            pnpm install --ignore-scripts

            # build & reload this bot
            cd /root/DiscordBots/${{ matrix.bot.folder }}
            pnpm run build || echo "No build script; skipping"

            # restart under the exact PM2 name
            pm2 restart ${{ matrix.bot.process }} \
                || pm2 start dist/index.js --name ${{ matrix.bot.process }} --update-env
