name: Build & Deploy All Bots

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bot:
          - name: triviaBot
            folder: triviabot
            process: russell
          - name: opie-bot
            folder: opie-bot
            process: opie-bot
          - name: embed-handler
            folder: Embed-Handler
            process: embed-handler
        #   - name: genie-bot
        #     folder: genie-bot
        #     process: genie-bot
        # …add more bots here

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{secrets.VPS_HOST}} >> ~/.ssh/known_hosts

      - name: Install & Build ${{ matrix.bot.name }}
        run: |
          cd ${{ matrix.bot.folder }}
          pnpm install --ignore-scripts
          pnpm run build || echo "No build script; skipping"

      - name: SSH Deploy ${{ matrix.bot.name }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd ~/${{ matrix.bot.folder }}
            git pull origin main
            pnpm install 
            pnpm run build || echo "No build script; skipping"
            pm2 restart ${{ matrix.bot.process }} || pm2 start dist/index.js --name ${{ matrix.bot.process }}
